# Generated by Django 5.1.7 on 2026-02-26 18:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universally unique identifier — distributed-safe, non-sequential.', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Primary login identifier. Must be unique across the platform.', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', help_text='Optional phone number for contact.', max_length=20)),
                ('bio', models.TextField(blank=True, default='', help_text='User biography/description.')),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture. Stored in MEDIA_ROOT/avatars/.', null=True, upload_to='avatars/%Y/%m/')),
                ('location', models.CharField(blank=True, default='', help_text='City or wilaya for proximity matching.', max_length=255)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0.0, help_text='Denormalized average rating (0.00–5.00). Updated by service layer after each review. Avoids expensive AVG() query on every profile view.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.PositiveIntegerField(default=0, help_text='Denormalized review count — updated alongside rating_avg.')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the user has verified their identity/email.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Account creation timestamp.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last profile update timestamp.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_index=True, help_text='First day of rental (inclusive).')),
                ('end_date', models.DateField(db_index=True, help_text='Last day of rental (inclusive).')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('payment_pending', 'Payment Pending'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('total_days', models.PositiveIntegerField(help_text='Number of rental days (inclusive of start and end).')),
                ('base_total', models.DecimalField(decimal_places=2, help_text='price_per_day × total_days (before discount).', max_digits=12)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, help_text='Applied discount rate (0.00, 0.10, or 0.20).', max_digits=4)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='base_total × discount_rate.', max_digits=12)),
                ('final_total', models.DecimalField(decimal_places=2, help_text='base_total - discount_amount. Amount the renter pays.', max_digits=12)),
                ('deposit', models.DecimalField(decimal_places=2, help_text='Snapshot of item.deposit_amount at booking time.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Denormalized owner FK — avoids item.owner join on booking queries. Set automatically from item.owner in service layer.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_owner', to=settings.AUTH_USER_MODEL)),
                ('renter', models.ForeignKey(help_text='The user requesting the rental.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_renter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name of the category.', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier. Must be unique.', max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, default='', help_text='Icon identifier (Lucide icon name or emoji).', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category. NULL for root-level categories.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Optional: the booking this conversation is about.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='core.booking')),
                ('participant_1', models.ForeignKey(help_text='First participant (lower UUID by convention).', on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_p1', to=settings.AUTH_USER_MODEL)),
                ('participant_2', models.ForeignKey(help_text='Second participant.', on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_p2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short descriptive title.', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the item, condition, and what is included.')),
                ('condition', models.CharField(choices=[('like_new', 'Like New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair')], default='good', max_length=20)),
                ('price_per_day', models.DecimalField(decimal_places=2, help_text='Base rental price per day in DA. Must be >= 0.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit_amount', models.DecimalField(decimal_places=2, help_text='Security deposit in DA. Refunded after safe return.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(help_text='Pickup location (city name or address string for MVP).', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the item is visible and bookable. Owner-controlled toggle.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Category classification. SET_NULL if category is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.category')),
                ('owner', models.ForeignKey(help_text='The user who listed this item.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.item'),
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Item photograph. Stored in MEDIA_ROOT/items/.', upload_to='items/%Y/%m/')),
                ('is_cover', models.BooleanField(default=False, help_text='Whether this is the primary display image.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order. Lower = first.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.item')),
            ],
            options={
                'verbose_name': 'Item Image',
                'verbose_name_plural': 'Item Images',
                'db_table': 'item_images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Message body text.')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the recipient has read this message.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('renter_to_owner', 'Renter → Owner'), ('owner_to_renter', 'Owner → Renter')], help_text='Who is reviewing whom in this booking.', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 (poor) to 5 (excellent).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(help_text='Written review text. Minimum 10 characters enforced in clean().')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.booking')),
                ('reviewed_user', models.ForeignKey(help_text='The user being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(help_text='The user writing the review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='idx_user_verified'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created_at'], name='idx_user_created'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='idx_category_parent'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='idx_category_slug'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_1'], name='idx_conv_p1'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['participant_2'], name='idx_conv_p2'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-updated_at'], name='idx_conv_updated'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('participant_1', 'participant_2', 'booking'), name='uq_conversation_participants_booking'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['owner'], name='idx_item_owner'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category'], name='idx_item_category'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_active', '-created_at'], name='idx_item_active_date'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['price_per_day'], name='idx_item_price'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['location'], name='idx_item_location'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_day__gte', 0)), name='ck_item_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__gte', 0)), name='ck_item_deposit_non_negative'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['item', 'status'], name='idx_booking_item_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['renter'], name='idx_booking_renter'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['owner'], name='idx_booking_owner'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='idx_booking_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start_date', 'end_date'], name='idx_booking_dates'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['-created_at'], name='idx_booking_created'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='ck_booking_date_order'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('renter', models.F('owner')), _negated=True), name='ck_booking_no_self_booking'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('total_days__gte', 1)), name='ck_booking_min_duration'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='idx_msg_conv_date'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='idx_msg_sender'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='idx_msg_read'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['booking'], name='idx_review_booking'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer'], name='idx_review_reviewer'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewed_user'], name='idx_review_reviewed'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='idx_review_created'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('booking', 'reviewer', 'direction'), name='uq_review_one_per_direction'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='ck_review_rating_range'),
        ),
    ]
