# Generated by Django 5.1.7 on 2026-02-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_overlap_exclusion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', True)), fields=('participant_1', 'participant_2'), name='uq_conversation_participants_no_booking'),
        ),
    ]
