# Generated by Django 5.1.7 on 2026-02-27 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conversation_null_booking_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Optional: the booking this conversation is about. CASCADE: deleting a booking removes its conversation (prevents SET_NULL conflicts with the partial unique constraint).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.booking'),
        ),
    ]
